runtime: python27
api_version: 1
threadsafe: yes

# Handlers define how to route requests to your application.
handlers:

- url: .*
  script: main.app

libraries:
- name: ssl
  version: latest

includes:
  - env_variables.yaml
